name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, thank you so much for reporting your first issue! This will surely help improve our code! 😊'
        pr-message: 'Hey, so cool to see this first PR of yours! New contributors deserve a special hug! 🤗'
